on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "HELOO"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: success()
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "JOB 2 is HEEERRRE!!!"      
