on: 
  push
jobs:
  job1:
    env:
      NAME: "SHAHD"
      WO: ${{vars.WORK}}
    runs-on: ubuntu-latest
    steps:
      - name: Display my name
        run: |
          echo ${{env.NAME}}
          echo $WO
