on: 
  push
jobs:
  job1:
    env:
      NAME: "SHAHD"
    runs-on: ubuntu-latest
    steps:
      - name: Debug - print
        run: env
      - name: Display my name
        env:
          WO: ${{vars.WORK}}
        run: |
          echo ${{env.NAME}}
          echo " A ${WO}"
