on: 
  push
jobs:
  job1:
    env:
      NAME: "SHAHD"
    environment: Test 
    runs-on: ubuntu-latest
    steps:
      - name: Debug - print
        run: env
      - name: Display my name
        run: |
          echo ${{env.NAME}}
          echo ${{vars.WORK}}
          echo ${{secrets.PASSWORD}}
